version: '3.5'  

services: 
    compose-frontend: 
      build: frontend/.
      ports: 
        - 5000:5000 
      container_name: compose_frontend
    compose-backend:
      build: backend/.
      restart: unless-stopped
      ports:
        - 8000:8000
      environment:
        - REDIS=compose_redis
        - DB_USERNAME=db_user
        - DB_PASSWORD=secret
        - DB_NAME=db_name
        - DB_HOST=compose_db
      depends_on:
        - compose_redis
        - compose_db
      container_name: compose_backend
    compose_redis:
      image: redis:buster
      container_name: compose_redis
    compose_db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=db_user
        - POSTGRES_DB=db_name
      container_name: compose_db
