version: '3.5'  

services: 
    kurkkumopo_frontend: 
      build: ml-kurkkumopo-frontend/.
      ports:
        - 3000:3000

    kurkkumopo_backend: 
      build: ml-kurkkumopo-backend/.
      volumes:
        - model:/src/model
      ports:
        - 5000:5000

    kurkkumopo_training: 
      build: ml-kurkkumopo-training/.
      volumes:
        - model:/src/model
        - imgs:/src/imgs

volumes:
  model:
  imgs:
